spring.application.name=auth-service

#spring data jpa
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate

#liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

#jwt
jwt.secret=${SECRET_KEY}
jwt.expiration-ms=${EXPIRATION_MS}